gpu: mali: remove TRACE_SYSTEM_STRING
This patch removes TRACE_SYSTEM_STRING from mali driver
because this definitions caused build warnings and errors.

include/trace/ftrace.h:724:15: error: implicit declaration of function '__stringfy' [-Werror=implicit-function-declaration]
 static struct ftrace_event_class __used __refdata event_class_##call = { \
               ^
include/trace/ftrace.h:60:2: note: in expansion of macro 'DECLARE_EVENT_CLASS'
  DECLARE_EVENT_CLASS(name,          \
  ^
drivers/gpu/arm/mali400/linux/./mali_linux_trace.h:39:1: note: in expansion of macro 'TRACE_EVENT'
 TRACE_EVENT(mali_timeline_event,
 ^
In file included from include/trace/ftrace.h:766:0,
                 from include/trace/define_trace.h:90,
                 from drivers/gpu/arm/mali400/linux/mali_linux_trace.h:161,
                 from drivers/gpu/arm/mali400/linux/mali_kernel_linux.c:61:
drivers/gpu/arm/mali400/linux/./mali_linux_trace.h:20:22: error: 'mali' undeclared here (not in a function)
 #define TRACE_SYSTEM mali
                      ^

Change-Id: I5cbfd90167b6c604f8c02588b8d8f7de46879a54
Signed-off-by: Chanho Park <chanho61.park@samsung.com>